// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentRequest struct {
	ID             pgtype.UUID        `json:"id"`
	SenderID       pgtype.UUID        `json:"sender_id"`
	RecipientEmail *string            `json:"recipient_email"`
	RecipientPhone *string            `json:"recipient_phone"`
	RecipientID    pgtype.UUID        `json:"recipient_id"`
	AmountMinor    int32              `json:"amount_minor"`
	Note           *string            `json:"note"`
	Status         string             `json:"status"`
	ShareToken     string             `json:"share_token"`
	IdempotencyKey *string            `json:"idempotency_key"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Phone       *string            `json:"phone"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
