// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentRequest = `-- name: CreatePaymentRequest :one
INSERT INTO payment_requests (
    sender_id, recipient_email, recipient_phone, recipient_id,
    amount_minor, note, share_token, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, now() + INTERVAL '7 days')
RETURNING id, sender_id, recipient_email, recipient_phone, recipient_id, amount_minor, note, status, share_token, idempotency_key, expires_at, created_at, updated_at
`

type CreatePaymentRequestParams struct {
	SenderID       pgtype.UUID `json:"sender_id"`
	RecipientEmail *string     `json:"recipient_email"`
	RecipientPhone *string     `json:"recipient_phone"`
	RecipientID    pgtype.UUID `json:"recipient_id"`
	AmountMinor    int32       `json:"amount_minor"`
	Note           *string     `json:"note"`
	ShareToken     string      `json:"share_token"`
}

func (q *Queries) CreatePaymentRequest(ctx context.Context, arg CreatePaymentRequestParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, createPaymentRequest,
		arg.SenderID,
		arg.RecipientEmail,
		arg.RecipientPhone,
		arg.RecipientID,
		arg.AmountMinor,
		arg.Note,
		arg.ShareToken,
	)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientEmail,
		&i.RecipientPhone,
		&i.RecipientID,
		&i.AmountMinor,
		&i.Note,
		&i.Status,
		&i.ShareToken,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentRequestByID = `-- name: GetPaymentRequestByID :one
SELECT
    pr.id, pr.sender_id, pr.recipient_email, pr.recipient_phone, pr.recipient_id, pr.amount_minor, pr.note, pr.status, pr.share_token, pr.idempotency_key, pr.expires_at, pr.created_at, pr.updated_at,
    CASE
        WHEN pr.status = 'pending' AND pr.expires_at < now() THEN 'expired'
        ELSE pr.status
    END AS display_status,
    s.email AS sender_email,
    s.display_name AS sender_display_name,
    r.email AS recipient_resolved_email,
    r.phone AS recipient_resolved_phone,
    r.display_name AS recipient_display_name
FROM payment_requests pr
JOIN users s ON s.id = pr.sender_id
LEFT JOIN users r ON r.id = pr.recipient_id
WHERE pr.id = $1
`

type GetPaymentRequestByIDRow struct {
	ID                     pgtype.UUID        `json:"id"`
	SenderID               pgtype.UUID        `json:"sender_id"`
	RecipientEmail         *string            `json:"recipient_email"`
	RecipientPhone         *string            `json:"recipient_phone"`
	RecipientID            pgtype.UUID        `json:"recipient_id"`
	AmountMinor            int32              `json:"amount_minor"`
	Note                   *string            `json:"note"`
	Status                 string             `json:"status"`
	ShareToken             string             `json:"share_token"`
	IdempotencyKey         *string            `json:"idempotency_key"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DisplayStatus          interface{}        `json:"display_status"`
	SenderEmail            string             `json:"sender_email"`
	SenderDisplayName      string             `json:"sender_display_name"`
	RecipientResolvedEmail *string            `json:"recipient_resolved_email"`
	RecipientResolvedPhone *string            `json:"recipient_resolved_phone"`
	RecipientDisplayName   *string            `json:"recipient_display_name"`
}

func (q *Queries) GetPaymentRequestByID(ctx context.Context, id pgtype.UUID) (GetPaymentRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentRequestByID, id)
	var i GetPaymentRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientEmail,
		&i.RecipientPhone,
		&i.RecipientID,
		&i.AmountMinor,
		&i.Note,
		&i.Status,
		&i.ShareToken,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayStatus,
		&i.SenderEmail,
		&i.SenderDisplayName,
		&i.RecipientResolvedEmail,
		&i.RecipientResolvedPhone,
		&i.RecipientDisplayName,
	)
	return i, err
}

const getPaymentRequestByShareToken = `-- name: GetPaymentRequestByShareToken :one
SELECT
    pr.id, pr.sender_id, pr.recipient_email, pr.recipient_phone, pr.recipient_id, pr.amount_minor, pr.note, pr.status, pr.share_token, pr.idempotency_key, pr.expires_at, pr.created_at, pr.updated_at,
    CASE
        WHEN pr.status = 'pending' AND pr.expires_at < now() THEN 'expired'
        ELSE pr.status
    END AS display_status,
    s.email AS sender_email,
    s.display_name AS sender_display_name,
    r.email AS recipient_resolved_email,
    r.phone AS recipient_resolved_phone,
    r.display_name AS recipient_display_name
FROM payment_requests pr
JOIN users s ON s.id = pr.sender_id
LEFT JOIN users r ON r.id = pr.recipient_id
WHERE pr.share_token = $1
`

type GetPaymentRequestByShareTokenRow struct {
	ID                     pgtype.UUID        `json:"id"`
	SenderID               pgtype.UUID        `json:"sender_id"`
	RecipientEmail         *string            `json:"recipient_email"`
	RecipientPhone         *string            `json:"recipient_phone"`
	RecipientID            pgtype.UUID        `json:"recipient_id"`
	AmountMinor            int32              `json:"amount_minor"`
	Note                   *string            `json:"note"`
	Status                 string             `json:"status"`
	ShareToken             string             `json:"share_token"`
	IdempotencyKey         *string            `json:"idempotency_key"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DisplayStatus          interface{}        `json:"display_status"`
	SenderEmail            string             `json:"sender_email"`
	SenderDisplayName      string             `json:"sender_display_name"`
	RecipientResolvedEmail *string            `json:"recipient_resolved_email"`
	RecipientResolvedPhone *string            `json:"recipient_resolved_phone"`
	RecipientDisplayName   *string            `json:"recipient_display_name"`
}

func (q *Queries) GetPaymentRequestByShareToken(ctx context.Context, shareToken string) (GetPaymentRequestByShareTokenRow, error) {
	row := q.db.QueryRow(ctx, getPaymentRequestByShareToken, shareToken)
	var i GetPaymentRequestByShareTokenRow
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientEmail,
		&i.RecipientPhone,
		&i.RecipientID,
		&i.AmountMinor,
		&i.Note,
		&i.Status,
		&i.ShareToken,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayStatus,
		&i.SenderEmail,
		&i.SenderDisplayName,
		&i.RecipientResolvedEmail,
		&i.RecipientResolvedPhone,
		&i.RecipientDisplayName,
	)
	return i, err
}

const getPaymentRequestRaw = `-- name: GetPaymentRequestRaw :one
SELECT id, sender_id, recipient_email, recipient_phone, recipient_id, amount_minor, note, status, share_token, idempotency_key, expires_at, created_at, updated_at FROM payment_requests WHERE id = $1
`

func (q *Queries) GetPaymentRequestRaw(ctx context.Context, id pgtype.UUID) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, getPaymentRequestRaw, id)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientEmail,
		&i.RecipientPhone,
		&i.RecipientID,
		&i.AmountMinor,
		&i.Note,
		&i.Status,
		&i.ShareToken,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncomingRequests = `-- name: ListIncomingRequests :many
SELECT
    pr.id, pr.sender_id, pr.recipient_email, pr.recipient_phone, pr.recipient_id, pr.amount_minor, pr.note, pr.status, pr.share_token, pr.idempotency_key, pr.expires_at, pr.created_at, pr.updated_at,
    CASE
        WHEN pr.status = 'pending' AND pr.expires_at < now() THEN 'expired'
        ELSE pr.status
    END AS display_status,
    s.email AS sender_email,
    s.display_name AS sender_display_name,
    r.email AS recipient_resolved_email,
    r.phone AS recipient_resolved_phone,
    r.display_name AS recipient_display_name
FROM payment_requests pr
JOIN users s ON s.id = pr.sender_id
LEFT JOIN users r ON r.id = pr.recipient_id
WHERE (pr.recipient_id = $1 OR pr.recipient_email = $2 OR pr.recipient_phone = $3)
  AND ($4::text IS NULL OR
       CASE
           WHEN $4::text = 'expired' THEN pr.status = 'pending' AND pr.expires_at < now()
           WHEN $4::text = 'pending' THEN pr.status = 'pending' AND pr.expires_at >= now()
           ELSE pr.status = $4::text
       END)
  AND ($5::text IS NULL OR
       COALESCE(s.email, '') ILIKE '%' || $5::text || '%' OR
       COALESCE(s.phone, '') ILIKE '%' || $5::text || '%' OR
       COALESCE(s.display_name, '') ILIKE '%' || $5::text || '%')
ORDER BY pr.created_at DESC
`

type ListIncomingRequestsParams struct {
	RecipientID    pgtype.UUID `json:"recipient_id"`
	RecipientEmail *string     `json:"recipient_email"`
	RecipientPhone *string     `json:"recipient_phone"`
	Status         *string     `json:"status"`
	Search         *string     `json:"search"`
}

type ListIncomingRequestsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	SenderID               pgtype.UUID        `json:"sender_id"`
	RecipientEmail         *string            `json:"recipient_email"`
	RecipientPhone         *string            `json:"recipient_phone"`
	RecipientID            pgtype.UUID        `json:"recipient_id"`
	AmountMinor            int32              `json:"amount_minor"`
	Note                   *string            `json:"note"`
	Status                 string             `json:"status"`
	ShareToken             string             `json:"share_token"`
	IdempotencyKey         *string            `json:"idempotency_key"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DisplayStatus          interface{}        `json:"display_status"`
	SenderEmail            string             `json:"sender_email"`
	SenderDisplayName      string             `json:"sender_display_name"`
	RecipientResolvedEmail *string            `json:"recipient_resolved_email"`
	RecipientResolvedPhone *string            `json:"recipient_resolved_phone"`
	RecipientDisplayName   *string            `json:"recipient_display_name"`
}

func (q *Queries) ListIncomingRequests(ctx context.Context, arg ListIncomingRequestsParams) ([]ListIncomingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingRequests,
		arg.RecipientID,
		arg.RecipientEmail,
		arg.RecipientPhone,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingRequestsRow{}
	for rows.Next() {
		var i ListIncomingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientEmail,
			&i.RecipientPhone,
			&i.RecipientID,
			&i.AmountMinor,
			&i.Note,
			&i.Status,
			&i.ShareToken,
			&i.IdempotencyKey,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayStatus,
			&i.SenderEmail,
			&i.SenderDisplayName,
			&i.RecipientResolvedEmail,
			&i.RecipientResolvedPhone,
			&i.RecipientDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingRequests = `-- name: ListOutgoingRequests :many
SELECT
    pr.id, pr.sender_id, pr.recipient_email, pr.recipient_phone, pr.recipient_id, pr.amount_minor, pr.note, pr.status, pr.share_token, pr.idempotency_key, pr.expires_at, pr.created_at, pr.updated_at,
    CASE
        WHEN pr.status = 'pending' AND pr.expires_at < now() THEN 'expired'
        ELSE pr.status
    END AS display_status,
    s.email AS sender_email,
    s.display_name AS sender_display_name,
    r.email AS recipient_resolved_email,
    r.phone AS recipient_resolved_phone,
    r.display_name AS recipient_display_name
FROM payment_requests pr
JOIN users s ON s.id = pr.sender_id
LEFT JOIN users r ON r.id = pr.recipient_id
WHERE pr.sender_id = $1
  AND ($2::text IS NULL OR
       CASE
           WHEN $2::text = 'expired' THEN pr.status = 'pending' AND pr.expires_at < now()
           WHEN $2::text = 'pending' THEN pr.status = 'pending' AND pr.expires_at >= now()
           ELSE pr.status = $2::text
       END)
  AND ($3::text IS NULL OR
       COALESCE(pr.recipient_email, '') ILIKE '%' || $3::text || '%' OR
       COALESCE(pr.recipient_phone, '') ILIKE '%' || $3::text || '%' OR
       COALESCE(r.email, '') ILIKE '%' || $3::text || '%' OR
       COALESCE(r.phone, '') ILIKE '%' || $3::text || '%')
ORDER BY pr.created_at DESC
`

type ListOutgoingRequestsParams struct {
	SenderID pgtype.UUID `json:"sender_id"`
	Status   *string     `json:"status"`
	Search   *string     `json:"search"`
}

type ListOutgoingRequestsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	SenderID               pgtype.UUID        `json:"sender_id"`
	RecipientEmail         *string            `json:"recipient_email"`
	RecipientPhone         *string            `json:"recipient_phone"`
	RecipientID            pgtype.UUID        `json:"recipient_id"`
	AmountMinor            int32              `json:"amount_minor"`
	Note                   *string            `json:"note"`
	Status                 string             `json:"status"`
	ShareToken             string             `json:"share_token"`
	IdempotencyKey         *string            `json:"idempotency_key"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DisplayStatus          interface{}        `json:"display_status"`
	SenderEmail            string             `json:"sender_email"`
	SenderDisplayName      string             `json:"sender_display_name"`
	RecipientResolvedEmail *string            `json:"recipient_resolved_email"`
	RecipientResolvedPhone *string            `json:"recipient_resolved_phone"`
	RecipientDisplayName   *string            `json:"recipient_display_name"`
}

func (q *Queries) ListOutgoingRequests(ctx context.Context, arg ListOutgoingRequestsParams) ([]ListOutgoingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingRequests, arg.SenderID, arg.Status, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutgoingRequestsRow{}
	for rows.Next() {
		var i ListOutgoingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientEmail,
			&i.RecipientPhone,
			&i.RecipientID,
			&i.AmountMinor,
			&i.Note,
			&i.Status,
			&i.ShareToken,
			&i.IdempotencyKey,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayStatus,
			&i.SenderEmail,
			&i.SenderDisplayName,
			&i.RecipientResolvedEmail,
			&i.RecipientResolvedPhone,
			&i.RecipientDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionStatus = `-- name: TransitionStatus :one
UPDATE payment_requests
SET status = $1, idempotency_key = $2, updated_at = now()
WHERE id = $3
  AND status = 'pending'
  AND expires_at > now()
RETURNING id, sender_id, recipient_email, recipient_phone, recipient_id, amount_minor, note, status, share_token, idempotency_key, expires_at, created_at, updated_at
`

type TransitionStatusParams struct {
	Status         string      `json:"status"`
	IdempotencyKey *string     `json:"idempotency_key"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) TransitionStatus(ctx context.Context, arg TransitionStatusParams) (PaymentRequest, error) {
	row := q.db.QueryRow(ctx, transitionStatus, arg.Status, arg.IdempotencyKey, arg.ID)
	var i PaymentRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientEmail,
		&i.RecipientPhone,
		&i.RecipientID,
		&i.AmountMinor,
		&i.Note,
		&i.Status,
		&i.ShareToken,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
