// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, phone, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, phone, display_name, created_at
`

type CreateUserParams struct {
	Email       string  `json:"email"`
	Phone       *string `json:"phone"`
	DisplayName string  `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Phone, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, display_name, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, display_name, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, email, phone, display_name, created_at FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const resolveRecipientByEmail = `-- name: ResolveRecipientByEmail :exec
UPDATE payment_requests
SET recipient_id = $1, updated_at = now()
WHERE recipient_email = $2 AND recipient_id IS NULL
`

type ResolveRecipientByEmailParams struct {
	RecipientID    pgtype.UUID `json:"recipient_id"`
	RecipientEmail *string     `json:"recipient_email"`
}

func (q *Queries) ResolveRecipientByEmail(ctx context.Context, arg ResolveRecipientByEmailParams) error {
	_, err := q.db.Exec(ctx, resolveRecipientByEmail, arg.RecipientID, arg.RecipientEmail)
	return err
}

const resolveRecipientByPhone = `-- name: ResolveRecipientByPhone :exec
UPDATE payment_requests
SET recipient_id = $1, updated_at = now()
WHERE recipient_phone = $2 AND recipient_id IS NULL
`

type ResolveRecipientByPhoneParams struct {
	RecipientID    pgtype.UUID `json:"recipient_id"`
	RecipientPhone *string     `json:"recipient_phone"`
}

func (q *Queries) ResolveRecipientByPhone(ctx context.Context, arg ResolveRecipientByPhoneParams) error {
	_, err := q.db.Exec(ctx, resolveRecipientByPhone, arg.RecipientID, arg.RecipientPhone)
	return err
}
