linters:
  enable:
    - errcheck
    - staticcheck
    - gosec
    - govet
    - ineffassign
    - unused
    - gocritic

linters-settings:
  gosec:
    excludes:
      - G114 # net/http serve without timeout (dev server)

run:
  timeout: 5m

issues:
  exclude-use-default: false
